name: Local Palindrome Deploy

on:
  push:
    branches: [ main ]

jobs:
  notify-server:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger local deploy script
        run: |
          curl -X POST http://172.16.2.57:5000/deploy
