name: Local Palindrome Deploy

on:
  push:
    branches: [ main ]

jobs:
  notify-server:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger local deploy script
        run: |
          curl -X POST  https://ngrok.com/r/http-request                                                                         
                                                                                
